---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	extract_category(extract_category)
	human_clarification(human_clarification)
	__end__([<p>__end__</p>]):::last
	__start__ --> extract_category;
	extract_category -. &nbsp;finish&nbsp; .-> __end__;
	extract_category -. &nbsp;clarify&nbsp; .-> human_clarification;
	human_clarification --> extract_category;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
